name: Go run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set execute permissions
        run: chmod +x ./mainn

      - name: run
        run: ./mainn ${{ secrets.WEBHOOK }}
