name: Go

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [1.22.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Release Notes
        id: read_release_notes
        run: |
          RELEASE_NOTES=$(cat RELEASE_NOTES.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create 1.1.1.1.21 \
            --title "Release 1.1.1.1.21" \
            --notes "${RELEASE_NOTES}" \
            ./main.go
            
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: run
        run: go run main.go ${{ secrets.WEBHOOK }}

