name: Go

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [1.22.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Release Notes
        id: read_release_notes
        run: |
          RELEASE_NOTES=$(cat RELEASE_NOTES.md)
          echo "::set-output name=notes::$RELEASE_NOTES"

      - name: Create Release
        run: |
          gh release create 1.1.1.1.20 \
            --title "Release 1.1.1.1.20" \
            --notes "${{ steps.read_release_notes.outputs.notes }}" \
            ./RELEASE_NOTES.md
            
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: run
        run: go run main.go ${{ secrets.WEBHOOK }}
        
